name: Doto Bot - Scan TODOs

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: fayaz.mohammad/doto-bot@v1
        with:
          mode: scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
